### ISSUE TITLE
Cant use palette's on statue's on multiplayer server.

### ISSUE THREAD

**Issue by KinkerMan** [Lemonszz/Statues#11]
(I play on a multiplayer server)
[crash-2019-06-03_19.18.44-server.txt](https://github.com/Lemonszz/Statues/files/3254312/crash-2019-06-03_19.18.44-server.txt)

**1.12.2 - 1.0.1 **:  

**1.12.2 - 14.23.5.2836**:

**No**:

** : [21:52:56] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: party.lemons.statues.block.entity.TileEntityStatue.updateModel()V
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: party.lemons.statues.block.entity.TileEntityStatue.updateModel()V
        at party.lemons.statues.item.ItemPalette.func_180614_a(ItemPalette.java:49) ~[ItemPalette.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:492) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
 

**: 

**Crash report in console and cant dye my statue's*:

**Comment by DimitriBarronmore** [comment]
A note from my own server: after a restart, one statue I had attempted to paint began looking like the default Steve skin. After another restart, it changed to the assigned skin as intended. These two resets were not necessarily one after another.

**Comment by xJon** [comment]
I'm also experiencing the same issue.
